### ISSUE TITLE
The greatest TUI client so far, bat the progress [bar] is absolute must!

### ISSUE THREAD

**Issue by ink-splatters** [aome510/hackernews-TUI#45]
Hi,

thanks a lot for just the greatest HN TUI! fantastic work! The only thing is lacking and, IMHO, it's a major issue (but very easy to add): the loading progress visualisation. 
Otherwise it feels like your brain is itching inside, lol :) Almost physical thing!

Or if by some reason there is one and I'm missing it... Just let me know :)

Thanks!

**Comment by aome510** [comment]
Hi @ink-splatters, thank you for your kind words.

Regarding the loading progress visualisation, are you referring the time when loading stories, comments, etc?

Currently there is a simple loading screen (not a progress bar) for those:


https://user-images.githubusercontent.com/40011582/141149270-00ec8d8a-83d9-4744-be5b-22eed95dce16.mov

One reason that I don't use progress bar is because it's hard to estimate the time needed to finish an API call to the Hacker News server.

**Comment by ink-splatters** [comment]
@aome510 thank you very much for getting back to me. It's sort of a shame I didn't notice it, maybe I need to check if I'm blue color - blind:)

but just in case if this feedback helps, you may want to make the progress bar to stand out more, e.g. by making it thicker :) just saying :)

Regarding the API call time: can't you rely on `Content-Length`? or it's not guaranteed to present? (you could then update the status every time you receive a new buffer).

**Comment by aome510** [comment]
> but just in case if this feedback helps, you may want to make the progress bar to stand out more, e.g. by making it thicker :) just saying :)

> Regarding the API call time: can't you rely on Content-Length? or it's not guaranteed to present? (you could then update the status every time you receive a new buffer).

Great! Thanks for the feedback. I'll look into those and see what I could do.
